# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('StatMethRank_rcpp_hello_world', PACKAGE = 'StatMethRank')
}

rcpp_my_test <- function(a, b) {
    .Call('StatMethRank_rcpp_my_test', PACKAGE = 'StatMethRank', a, b)
}

